export const SITE = "https://thesis.scapedatasolutions.com";
export const BRAND = "Scape Data Solutions";
export const LOGO = "/Images/site-images/logo.svg";
export const LOGO_PNG = "/Images/site-images/logo-image.png";

export const CATEGORIES = [
  { id: "core", title: "Thesis and core analysis" },
  { id: "prep", title: "Data preparation" },
  { id: "scales", title: "Questionnaires and scales" },
  { id: "advanced", title: "Advanced models" },
];

export const landingPages = [
  /* ------------------------------------------------------------ 1 */
  {
    slug: "spss-data-analysis-help", short: "SPSS Data Analysis Help", category: "core", eyebrow: "SPSS",
    title: "SPSS Data Analysis Help for Thesis & Dissertations | Scape Data",
    description: "SPSS data analysis help: we choose the right test for each objective, check assumptions, run it and return APA tables, syntax and plain-English interpretation.",
    keywords: "SPSS data analysis help, SPSS help for students, SPSS thesis analysis, hire SPSS expert, SPSS assignment help",
    h1: "SPSS data analysis help for your thesis, dissertation or research paper",
    intro: "Send the .sav, Excel or CSV file and your research objectives. We pick the test each objective actually needs, check the assumptions, run it in SPSS, and hand back clean APA tables, the syntax, and a write-up you understand well enough to defend.",
    problems: [
      "Your objectives say 'determine the relationship' or 'establish the effect' and you cannot tell which test that means",
      "Levene's test, Shapiro-Wilk or Durbin-Watson came back significant and you do not know what happens next",
      "SPSS produced fourteen tables and your supervisor wants one",
      "Your panel returned Chapter 4 with the comment 'justify your choice of test'",
    ],
    steps: [
      { t: "Audit the file", d: "Variable types, labels, missing values and coding errors are fixed before any test is run." },
      { t: "Map objectives to tests", d: "A written analysis plan lists the test for each objective. You approve it first." },
      { t: "Run and verify", d: "Normality, homogeneity, linearity and outliers are checked. Non-parametric tests are used when assumptions fail." },
      { t: "Deliver", d: "Output file, syntax, cleaned .sav, APA tables and a plain-language explanation of every result." },
    ],
    deliverables: [
      "Descriptive statistics, frequencies and cross-tabulations",
      "T-tests, ANOVA, ANCOVA, MANOVA, chi-square, Mann-Whitney, Kruskal-Wallis, Wilcoxon",
      "Pearson and Spearman correlation, linear, multiple and logistic regression",
      "Cronbach's alpha and exploratory factor analysis",
      "The .sps syntax file and cleaned .sav so every number can be reproduced",
      "Effect sizes (Cohen's d, eta squared, odds ratios) reported next to every p-value",
    ],
    mistakes: [
      { t: "Running t-tests on single Likert items", d: "A single Likert item is ordinal. Build a composite score from a reliable scale, or use Mann-Whitney and Kruskal-Wallis." },
      { t: "Reporting p-values without effect sizes", d: "Examiners increasingly ask how big the effect is, not only whether it is significant. Report d, eta squared or odds ratios." },
      { t: "Treating Shapiro-Wilk as the final word on normality", d: "With a few hundred cases it flags trivial deviations. Read skewness, kurtosis and the Q-Q plot before abandoning a parametric test." },
    ],
    example: {
      setup: "Objective: determine whether job satisfaction differs between permanent and contract staff. Test: independent-samples t-test (Levene's test non-significant, equal variances assumed).",
      head: ["Group", "n", "M", "SD"],
      rows: [["Permanent", "112", "3.91", "0.62"], ["Contract", "98", "3.54", "0.71"]],
      note: "Written up as: Permanent staff reported higher satisfaction (M = 3.91, SD = 0.62) than contract staff (M = 3.54, SD = 0.71), t(208) = 4.03, p < .001, d = 0.56.",
    },
    guide: {
      title: "Which test fits your objective?",
      head: ["If the objective says", "Your variables", "Usual test"],
      rows: [
        ["Compare two groups", "Numeric outcome, 2 groups", "Independent t-test or Mann-Whitney U"],
        ["Compare three or more groups", "Numeric outcome, 3+ groups", "One-way ANOVA or Kruskal-Wallis"],
        ["Relationship between two variables", "Numeric or ordinal pair", "Pearson or Spearman correlation"],
        ["Association between categories", "Two categorical variables", "Chi-square or Fisher's exact"],
        ["Predict or explain an outcome", "Numeric or binary outcome", "Multiple or logistic regression"],
      ],
    },
    faqs: [
      { q: "What do I need to send?", a: "Your dataset (.sav, Excel or CSV), your research objectives or hypotheses, and any supervisor comments. A questionnaire or codebook helps a lot if you have one." },
      { q: "Can I get the SPSS syntax and the cleaned file back?", a: "Yes. You receive the output, the formatted tables, the working .sav and the .sps syntax so you can reproduce and defend every number." },
      { q: "My supervisor wants a different test. Can you redo it?", a: "Yes. Revisions to match supervisor or panel feedback are part of the service. Send the comments and we adjust the analysis and the write-up." },
      { q: "Do you work with other software?", a: "Yes. If your institution requires R, Stata, Jamovi, JASP or Excel, tell us in the request form and we confirm availability." },
    ],
    related: ["regression-analysis-help", "likert-scale-data-analysis", "research-results-interpretation"],
  },
  /* ------------------------------------------------------------ 2 */
  {
    slug: "thesis-data-analysis-help", short: "Thesis Data Analysis Help", category: "core", eyebrow: "Masters and PhD",
    title: "Thesis Data Analysis Help | Masters & PhD Statistics | Scape Data",
    description: "Thesis data analysis help for masters and PhD students: an objective-by-objective analysis plan, correct tests, APA tables and viva preparation on your methods.",
    keywords: "thesis data analysis help, dissertation statistical analysis, masters thesis statistics, PhD data analysis help, data analysis for thesis",
    h1: "Thesis data analysis help: from raw data to a Chapter 4 you can defend",
    intro: "Your analysis has to answer your objectives, match your methodology chapter and survive questions at the viva. We build the analysis plan from your proposal, run it, and explain every choice, so your defence is not the first time you hear it.",
    problems: [
      "Your methodology chapter promises tests you have never run",
      "You have data from 300 respondents and no plan for answering the objectives",
      "Your supervisor said 'strengthen the statistical justification'",
      "The viva is in three weeks and you cannot explain why you used that test",
    ],
    steps: [
      { t: "Read your proposal", d: "Objectives, hypotheses, sampling and instruments from Chapters 1 and 3." },
      { t: "Write the analysis plan", d: "Each objective gets a named method, its variables and the table it will produce. You approve it before anything is run." },
      { t: "Run and check", d: "Assumptions tested, alternatives used when they fail, every decision logged." },
      { t: "Hand over and brief", d: "Results, tables, interpretation and a short list of likely panel questions with answers." },
    ],
    deliverables: [
      "Objective-by-objective analysis plan",
      "Every test run with assumption checks",
      "APA-formatted tables and figures",
      "Interpretation paragraphs you can adapt for Chapter 4",
      "Likely viva questions on your methods, with suggested answers",
      "Syntax or script to reproduce all results",
    ],
    mistakes: [
      { t: "Choosing tests before reading the objectives", d: "The objective decides the test. 'Establish the relationship' and 'compare groups' need different methods." },
      { t: "A Chapter 3 that does not match Chapter 4", d: "Panels cross-check them. If you wrote Pearson and ran Spearman, state the failed assumption that justified the switch." },
      { t: "Analysing everything that can be analysed", d: "Tables that do not answer an objective weaken the chapter. Every output should map to a research question or hypothesis." },
    ],
    example: {
      setup: "This is the kind of analysis plan you approve first, before any test is run.",
      head: ["Objective", "Method", "Output"],
      rows: [
        ["1. Describe respondent profile", "Frequencies and percentages", "Table 4.1"],
        ["2. Assess level of technology adoption", "Mean, SD, one-sample t-test against 3.0", "Table 4.2"],
        ["3. Determine effect of training on performance", "Multiple regression", "Table 4.3"],
        ["4. Compare adoption across departments", "One-way ANOVA with Tukey post-hoc", "Table 4.4"],
      ],
      note: "Every row maps to a numbered table in Chapter 4, so nothing is analysed that does not answer an objective.",
    },
    guide: {
      title: "What your study design usually needs",
      head: ["Study design", "Typical analysis"],
      rows: [
        ["Descriptive survey", "Frequencies, means, standard deviations, cross-tabulations"],
        ["Correlational study", "Pearson or Spearman correlation, multiple regression"],
        ["Experimental or quasi-experimental", "t-tests, ANOVA, ANCOVA, MANOVA"],
        ["Survey with validated scales", "Reliability, factor analysis, regression or SEM"],
      ],
    },
    faqs: [
      { q: "Do you support both masters and PhD theses?", a: "Yes. We support undergraduate, masters and doctoral research across social sciences, health, business, education, agriculture and more." },
      { q: "Can you work from the methodology I already wrote?", a: "Yes. Share Chapter 3 and we align the analysis to the design, sampling and variables you described, and flag any mismatch before running anything." },
      { q: "Will I understand the results well enough to defend them?", a: "That is the aim. Each result comes with a plain-language explanation and the reasoning behind the test choice." },
      { q: "How fast can you deliver?", a: "It depends on dataset size and complexity. State your deadline in the form and we confirm what is achievable before you commit to anything." },
    ],
    related: ["chapter-4-results-writing-help", "spss-data-analysis-help", "sample-size-calculation-help"],
  },
  /* ------------------------------------------------------------ 3 */
  {
    slug: "research-data-cleaning-service", short: "Research Data Cleaning", category: "prep", eyebrow: "Data preparation",
    title: "Research Data Cleaning Service | Fix Messy Survey Data | Scape Data",
    description: "Research data cleaning for surveys and thesis datasets: duplicates, missing values, recoding, reverse-coded items and outliers, with a full change log.",
    keywords: "research data cleaning service, clean survey data, data cleaning for thesis, recode SPSS data, fix messy dataset",
    h1: "Research data cleaning: turn a messy export into analysis-ready data",
    intro: "Bad data produces bad results, and no test fixes that. Send the raw spreadsheet and we repair errors, handle missing values, standardise coding and build scale scores, with a log of every change so your process stays transparent.",
    problems: [
      "Duplicate or half-complete responses from online or field collection",
      "'Male', 'male', 'M' and 'MALE' in the same column",
      "Missing values and no plan for handling them",
      "Ages of 214 and incomes of zero distorting your results",
    ],
    steps: [
      { t: "Profile the raw file", d: "We scan every variable for type errors, duplicates, impossible values and missing patterns. Your original stays untouched." },
      { t: "Decide the rules", d: "You get a short list of proposed fixes, such as how to treat missing values and which cases to exclude. You approve them." },
      { t: "Clean and recode", d: "Labels, value codes, reverse-coded items and computed scale scores are applied on a working copy." },
      { t: "Document", d: "Cleaned file, codebook and a change log showing every edit, which your methodology chapter can cite." },
    ],
    deliverables: [
      "Cleaned dataset in Excel, CSV or SPSS format",
      "Variable names, labels and value labels",
      "A codebook for the whole dataset",
      "Missing-data and outlier report with recommended handling",
      "A change log documenting every edit",
      "Computed composite scores, including reverse-coded items",
    ],
    mistakes: [
      { t: "Deleting outliers because they look odd", d: "Check whether a value is an error or a real extreme. Real extremes are reported and handled, not silently removed." },
      { t: "Forgetting to reverse-code negative items", d: "Unreversed items drag Cronbach's alpha down and produce nonsense composite scores." },
      { t: "Cleaning the only copy of the data", d: "Always keep the raw file untouched. A change log lets you defend every difference between raw and cleaned." },
    ],
    example: {
      setup: "Typical issues found in a 400-row survey export, and what is done about each.",
      head: ["Issue", "Example", "Fix applied"],
      rows: [
        ["Inconsistent labels", "Male / male / M / MALE", "Recoded to 1 = Male"],
        ["Duplicate submissions", "Same email, two entries", "Latest kept, ID logged"],
        ["Impossible value", "Age = 214", "Verified or set to missing"],
        ["Straight-lining", "Same answer on 30 items", "Flagged for exclusion decision"],
        ["Reverse-coded items", "Q7 and Q12 not reversed", "Reversed before scoring"],
      ],
      note: "Illustrative example. Every real engagement ends with a change log like this for your own data.",
    },
    guide: {
      title: "How missing data is usually handled",
      head: ["Missing", "Pattern", "Typical handling"],
      rows: [
        ["Under 5% of values", "Looks random", "Listwise deletion is usually acceptable"],
        ["5% to 20%", "Random or unclear", "Multiple imputation or EM, reported in methods"],
        ["Over 20% on one item", "Probably systematic", "Review the item; consider dropping it and say so"],
        ["Respondent left most blank", "Dropout", "Remove the case and report how many"],
      ],
    },
    faqs: [
      { q: "Will you change my original data?", a: "No. We work on a copy and keep your raw file intact, with a change log for every correction." },
      { q: "Can you clean data from Google Forms, KoboToolbox or ODK?", a: "Yes. We regularly restructure these exports into a tidy, labelled, analysis-ready dataset." },
      { q: "Do you also analyse after cleaning?", a: "If you want. Many students combine cleaning and analysis in one request." },
      { q: "How do you decide what counts as an outlier?", a: "We use boxplots, z-scores and subject knowledge together, then ask you or your supervisor's guidance before removing anything." },
    ],
    related: ["kobotoolbox-odk-data-analysis-help", "questionnaire-data-analysis-help", "spss-data-analysis-help"],
  },
  /* ------------------------------------------------------------ 4 */
  {
    slug: "questionnaire-data-analysis-help", short: "Questionnaire Data Analysis", category: "scales", eyebrow: "Surveys",
    title: "Questionnaire & Survey Data Analysis Help for Research | Scape Data",
    description: "Questionnaire data analysis help: coding, section-by-section descriptives, mean interpretation, reliability and tests of demographics against responses.",
    keywords: "questionnaire data analysis help, survey data analysis service, analyse questionnaire for thesis, research survey statistics",
    h1: "Questionnaire data analysis: from returned forms to findings by objective",
    intro: "You collected the responses. Now they have to become tables that answer each objective. We code the questionnaire, check reliability, analyse section by section and interpret the means in the way your university expects.",
    problems: [
      "You do not know how to turn 40 questionnaire items into tables for four objectives",
      "You need means, standard deviations and a clear reading of agreement levels",
      "You must test whether demographics change the responses",
      "Your questionnaire has sections that need different analyses",
    ],
    steps: [
      { t: "Code the questionnaire", d: "A codebook and variable structure are built from your instrument, including multiple-response items." },
      { t: "Check reliability", d: "Cronbach's alpha for every construct. Weak items are flagged before any composite score is made." },
      { t: "Analyse by section", d: "Frequencies for demographics, means and SDs for scales, tests where objectives need comparisons or relationships." },
      { t: "Interpret and format", d: "Tables are labelled for your report, with a sentence of interpretation under each." },
    ],
    deliverables: [
      "Coding structure and codebook for your questionnaire",
      "Frequencies for demographics and multiple-response items",
      "Means, standard deviations and agreement-level interpretation",
      "Cronbach's alpha for each construct",
      "Chi-square, correlation and group comparisons where objectives need them",
      "Tables and charts formatted for your report",
    ],
    mistakes: [
      { t: "Interpreting means without a stated scale", d: "State how you read the mean. A 5-point scale needs class intervals such as 3.41 to 4.20 = Agree, defined in your methodology." },
      { t: "Ignoring non-response patterns", d: "Report the response rate and explain how blanks were handled." },
      { t: "Comparing every demographic with every item", d: "Test only what your objectives or hypotheses call for. Dozens of unplanned tests produce false positives." },
    ],
    example: {
      setup: "A Likert section reported the way most universities expect it (5-point scale).",
      head: ["Item", "Mean", "SD", "Interpretation"],
      rows: [
        ["Management communicates clearly", "3.82", "0.91", "Agree"],
        ["I understand my targets", "4.11", "0.74", "Agree"],
        ["Feedback is timely", "2.94", "1.08", "Neutral"],
      ],
      note: "Illustrative example, not client data.",
    },
    guide: {
      title: "Reading means on a 5-point scale",
      head: ["Mean range", "Interpretation"],
      rows: [
        ["1.00 to 1.80", "Strongly disagree"],
        ["1.81 to 2.60", "Disagree"],
        ["2.61 to 3.40", "Neutral"],
        ["3.41 to 4.20", "Agree"],
        ["4.21 to 5.00", "Strongly agree"],
      ],
    },
    faqs: [
      { q: "Can you work from a paper questionnaire?", a: "If responses are entered into Excel or any spreadsheet we take it from there. Share the questionnaire so we can build the codebook." },
      { q: "What if my sample size is small?", a: "We recommend methods that suit small samples, including non-parametric options, and note the limitations you should state." },
      { q: "Can you handle open-ended questions too?", a: "Yes. We can code responses into themes and report counts, or hand you a coded sheet for your own write-up." },
      { q: "Do you include interpretation or only tables?", a: "Both. Each table comes with a short interpretation you can adapt to your chapter." },
    ],
    related: ["likert-scale-data-analysis", "cronbach-alpha-reliability-analysis", "research-data-cleaning-service"],
  },
  /* ------------------------------------------------------------ 5 */
  {
    slug: "excel-statistical-analysis-help", short: "Excel Statistical Analysis", category: "core", eyebrow: "Microsoft Excel",
    title: "Excel Statistical Analysis Help | ToolPak, Regression & Charts | Scape Data",
    description: "Excel statistical analysis help: Data Analysis ToolPak, regression, t-tests, ANOVA, pivot tables and charts, with live formulas you can audit.",
    keywords: "Excel statistical analysis help, Excel data analysis for students, Excel regression help, Data Analysis ToolPak, Excel assignment help",
    h1: "Excel statistical analysis help: regression, tests and charts that stay auditable",
    intro: "Excel handles real statistics once the data is structured and the right tool is chosen. We build the workbook, run the analysis with live formulas, label the charts, and explain each output so you can follow and reproduce it.",
    problems: [
      "The Data Analysis ToolPak is not showing in your Excel, or its output makes no sense",
      "LINEST, T.TEST or CORREL returns an error or a number you cannot interpret",
      "You need pivot tables or a summary dashboard from raw rows",
      "Your assignment requires regression and hypothesis testing in Excel specifically",
    ],
    steps: [
      { t: "Structure the sheet", d: "One variable per column, one case per row, clean headers and no merged cells." },
      { t: "Choose the Excel tool", d: "ToolPak for packaged tests, functions for live formulas, pivot tables for summaries." },
      { t: "Run and label", d: "Each output is labelled with what it measures. Charts get titles, axes and units." },
      { t: "Explain", d: "A short written note beside each result explains what it means and what to report." },
    ],
    deliverables: [
      "A tidy, formula-driven workbook you can trace",
      "Descriptive statistics, t-tests, ANOVA and correlation",
      "Simple and multiple regression with coefficients explained",
      "Pivot tables and clear charts",
      "Instructions to enable the ToolPak if it is missing",
    ],
    mistakes: [
      { t: "Pasting ToolPak output as the final table", d: "Raw ToolPak output is not report-ready. Round, relabel and keep only what answers the question." },
      { t: "Reading the wrong t-test", d: "Paired, equal-variance and unequal-variance tests give different answers. Choosing the wrong one changes your conclusion." },
      { t: "Hard-coding results", d: "Typed numbers cannot be audited. Live formulas let you and your lecturer trace every figure." },
    ],
    example: {
      setup: "Multiple regression from the ToolPak, n = 150: R-squared = 0.46, predicting exam score.",
      head: ["Term", "Coefficient", "p-value"],
      rows: [["Intercept", "1.82", ".003"], ["Study hours", "0.41", "< .001"], ["Attendance (%)", "0.02", ".048"]],
      note: "Illustrative example. Study hours is the strongest predictor: each extra hour is associated with a 0.41-point higher score, holding attendance constant.",
    },
    guide: {
      title: "What you need in Excel, and what we use",
      head: ["You need", "Excel tool"],
      rows: [
        ["Averages, spread, counts", "AVERAGE, STDEV.S, COUNTIF or ToolPak Descriptive Statistics"],
        ["Compare two means", "T.TEST or ToolPak t-Test (paired, equal or unequal variance)"],
        ["Correlation", "CORREL or ToolPak Correlation"],
        ["Summaries by group", "PivotTables"],
        ["Regression", "LINEST or ToolPak Regression"],
      ],
    },
    faqs: [
      { q: "Can you do regression in Excel?", a: "Yes. We run simple and multiple regression and explain coefficients, R-squared and significance." },
      { q: "Will the workbook use live formulas?", a: "Yes wherever sensible, so you can trace and update every calculation yourself." },
      { q: "My Excel has no Data Analysis button. Why?", a: "The ToolPak is an add-in that has to be enabled under File, Options, Add-ins. We include the steps for Windows and Mac." },
      { q: "Can you move the analysis to SPSS later?", a: "Yes. If your project needs deeper statistics we transfer and extend it in SPSS." },
    ],
    related: ["research-data-cleaning-service", "regression-analysis-help", "questionnaire-data-analysis-help"],
  },
  /* ------------------------------------------------------------ 6 */
  {
    slug: "research-results-interpretation", short: "Research Results Interpretation", category: "core", eyebrow: "Interpretation",
    title: "Research Results Interpretation | Explain SPSS & Statistical Output | Scape Data",
    description: "Don't understand your output? We explain p-values, coefficients, ANOVA, regression and effect sizes in clear academic language tied to your hypotheses.",
    keywords: "interpret SPSS output, research results interpretation, explain regression results, interpret p-value, statistical output explained",
    h1: "Research results interpretation: know exactly what your output means",
    intro: "You ran the tests. Now you have to explain them to a supervisor. Send the output and your objectives, and we translate every table into findings that link to your hypotheses and read like academic writing.",
    problems: [
      "You can see p = .003 but cannot say what it means for your hypothesis",
      "Coefficients, odds ratios and effect sizes are not clear to you",
      "Your results contradict your expectations and you need to discuss why",
      "Your supervisor asked for 'deeper interpretation'",
    ],
    steps: [
      { t: "Send the output", d: "Screenshots, SPSS output, R output or Excel tables. Your objectives help but raw data is usually not needed." },
      { t: "Line-by-line reading", d: "Each table is read in order: what was tested, what the key numbers are, what decision follows." },
      { t: "Write it up", d: "Interpretation paragraphs in academic style, with hypotheses accepted or rejected." },
      { t: "Link and limit", d: "Findings are tied to objectives, with notes on limitations and how to discuss them." },
    ],
    deliverables: [
      "A walk-through of every table in your output",
      "Written interpretation in academic style",
      "Decisions on each hypothesis, with reasons",
      "Discussion of non-significant or unexpected results",
      "Limitations you can cite honestly",
    ],
    mistakes: [
      { t: "Saying 'accepted the null hypothesis'", d: "You fail to reject it. The distinction matters to examiners." },
      { t: "Treating significance as importance", d: "With a large sample, tiny effects are significant. Report the effect size and what it means in practice." },
      { t: "Hiding a non-significant result", d: "A null result is still a finding. Report it, explain it and discuss possible reasons." },
    ],
    example: {
      setup: "A common regression table read line by line.",
      head: ["What SPSS shows", "What it means"],
      rows: [
        ["Sig. = .003", "If there were no real effect, a result this extreme would occur about 0.3% of the time: reject the null."],
        ["B = 0.41", "Each extra study hour is associated with a 0.41-point higher score, other variables held constant."],
        ["R squared = .46", "The model accounts for 46% of the variance in scores."],
        ["VIF = 1.3", "No multicollinearity concern (a common cut-off is 5 or 10)."],
      ],
      note: "Illustrative example.",
    },
    guide: {
      title: "How big is the effect?",
      head: ["Measure", "Small", "Medium", "Large"],
      rows: [["Cohen's d", "0.20", "0.50", "0.80"], ["Pearson r", ".10", ".30", ".50"], ["Partial eta squared", ".01", ".06", ".14"]],
    },
    faqs: [
      { q: "Do I need to send my raw data?", a: "Not always. For interpretation alone, the output tables and your objectives are usually enough." },
      { q: "Can you help with non-significant results?", a: "Yes. A non-significant result is a finding. We help you report and discuss it properly." },
      { q: "Will this help me defend my results?", a: "That is the goal. You should understand each result well enough to explain it in your own words." },
      { q: "Can you check my interpretation instead of writing it?", a: "Yes. Send your draft paragraphs and we correct statistical errors and wording." },
    ],
    related: ["chapter-4-results-writing-help", "regression-analysis-help", "spss-data-analysis-help"],
  },
  /* ------------------------------------------------------------ 7 */
  {
    slug: "regression-analysis-help", short: "Regression Analysis Help", category: "core", eyebrow: "Regression",
    title: "Regression Analysis Help | Linear, Multiple, Logistic | Scape Data",
    description: "Regression analysis help: linear, multiple, hierarchical, logistic and ordinal models with assumption diagnostics and plain-English coefficient interpretation.",
    keywords: "regression analysis help, multiple regression help, logistic regression help, hierarchical regression, regression assumptions",
    h1: "Regression analysis help: the right model, tested and explained",
    intro: "Regression is where most analysis chapters go wrong. We choose the model that matches your dependent variable, test the assumptions, fit it, and explain every coefficient so you can report and defend it.",
    problems: [
      "You are not sure whether your outcome needs linear or logistic regression",
      "VIF, heteroscedasticity or non-normal residuals are showing up",
      "You cannot interpret B, beta, odds ratios or R-squared",
      "You need to compare nested or hierarchical models",
    ],
    steps: [
      { t: "Match model to outcome", d: "The type of dependent variable decides the family: continuous, binary, ordinal or count." },
      { t: "Diagnose first", d: "Linearity, independence, homoscedasticity, residual normality, multicollinearity and influential cases." },
      { t: "Fit and compare", d: "Final model, plus hierarchical blocks or alternatives where theory needs them." },
      { t: "Interpret", d: "Coefficients, fit statistics and a results paragraph for each model." },
    ],
    deliverables: [
      "Model specification matched to your variables",
      "Assumption diagnostics with plots",
      "Coefficient tables with interpretation",
      "Model fit and comparison statistics",
      "Moderation or interaction terms if your hypotheses call for them",
    ],
    mistakes: [
      { t: "Using linear regression on a yes/no outcome", d: "Binary outcomes need logistic regression. Linear models give impossible probabilities." },
      { t: "Entering predictors with no theory", d: "Stuffing in every variable inflates R-squared and weakens the model. Justify each predictor." },
      { t: "Reading beta weights as causes", d: "Cross-sectional regression shows association. Claim causation only if your design supports it." },
    ],
    example: {
      setup: "Binary logistic regression: did the respondent adopt mobile banking (1 = yes)?",
      head: ["Predictor", "B", "Odds ratio", "p"],
      rows: [["Age", "0.03", "1.03", ".021"], ["Female", "-0.62", "0.54", ".004"], ["Prior training", "0.91", "2.48", "< .001"]],
      note: "Illustrative example. Prior training raises the odds of adoption about 2.5 times, controlling for age and sex.",
    },
    guide: {
      title: "Which regression for which outcome?",
      head: ["Dependent variable", "Model", "Key check"],
      rows: [
        ["Continuous (income, score)", "Linear or multiple regression", "Residual normality, homoscedasticity"],
        ["Binary (yes/no, adopt/not)", "Binary logistic", "Events per predictor, fit tests"],
        ["Ordered categories (Likert)", "Ordinal logistic", "Proportional odds"],
        ["Counts (visits, incidents)", "Poisson or negative binomial", "Overdispersion"],
        ["Time until an event", "Cox regression", "Proportional hazards"],
      ],
    },
    faqs: [
      { q: "Which regression types do you cover?", a: "Simple, multiple, hierarchical, binary, multinomial and ordinal logistic, plus moderation and mediation on request." },
      { q: "What if the assumptions are violated?", a: "We test remedies such as transformations, robust standard errors or a different model, and explain the trade-offs." },
      { q: "Can you work in R, Stata or Python?", a: "Yes. Tell us your preferred software in the request form and we confirm availability." },
      { q: "Can you explain the results to me as well?", a: "Yes. The write-up covers each coefficient and the model as a whole, in plain language." },
    ],
    related: ["mediation-moderation-analysis-help", "research-results-interpretation", "spss-data-analysis-help"],
  },
  /* ------------------------------------------------------------ 8 */
  {
    slug: "chapter-4-results-writing-help", short: "Chapter 4 Results Writing", category: "core", eyebrow: "Chapter 4",
    title: "Chapter 4 Results & Findings Help | Dissertation Data Presentation | Scape Data",
    description: "Help writing Chapter 4: structure by objective, formatted tables and charts, correct reporting formats and discussion-ready summaries of your findings.",
    keywords: "chapter 4 results help, dissertation findings chapter, thesis results chapter, presenting statistical results, data presentation",
    h1: "Chapter 4 help: present your findings clearly, objective by objective",
    intro: "The analysis is done but the chapter is not. We structure Chapter 4 around your objectives, format every table and chart, and write the narrative around the numbers in the reporting style your institution expects.",
    problems: [
      "You do not know how to organise Chapter 4 objective by objective",
      "Your tables and charts look inconsistent across the chapter",
      "You have results but struggle to describe them academically",
      "Your supervisor wants clearer links between findings and the literature",
    ],
    steps: [
      { t: "Share outputs and objectives", d: "Analysis outputs, your objectives and any chapter template from your department." },
      { t: "Build the skeleton", d: "Sections and table numbers are set to your objectives before any writing starts." },
      { t: "Write and format", d: "Tables, figures and interpretation are written to your referencing style, usually APA, Harvard or Chicago." },
      { t: "Revise", d: "Supervisor comments are handled until the chapter is accepted." },
    ],
    deliverables: [
      "Chapter structure aligned to your objectives",
      "Consistent, correctly numbered tables and figures",
      "Descriptive and inferential results written up",
      "A summary of findings that feeds your discussion chapter",
      "Revisions to meet supervisor feedback",
    ],
    mistakes: [
      { t: "Dumping software output into the chapter", d: "Screenshots are not tables. Rebuild each in the required format with only the relevant numbers." },
      { t: "Describing a table by repeating its numbers", d: "Say what the numbers show and why it matters. The reader can see the figures." },
      { t: "Mixing results and discussion", d: "Chapter 4 reports findings. Comparison with the literature belongs in Chapter 5 unless your department says otherwise." },
    ],
    example: {
      setup: "A typical Chapter 4 skeleton we agree with you first.",
      head: ["Section", "Contents"],
      rows: [
        ["4.1 Response rate and reliability", "Return rate, Cronbach's alpha table"],
        ["4.2 Respondent profile", "Demographic tables with one paragraph per variable"],
        ["4.3 Objective 1", "Descriptives, table, interpretation"],
        ["4.4 Hypothesis tests", "Test, statistic, p-value, decision"],
        ["4.5 Summary of findings", "One paragraph per objective"],
      ],
      note: "Illustrative example.",
    },
    guide: {
      title: "How to report common results (APA style)",
      head: ["Test", "Report like this"],
      rows: [
        ["Independent t-test", "t(df) = x.xx, p = .xxx, d = x.xx"],
        ["One-way ANOVA", "F(df1, df2) = x.xx, p = .xxx, eta squared = .xx"],
        ["Chi-square", "chi-square(df, N = n) = x.xx, p = .xxx, Cramer's V = .xx"],
        ["Correlation", "r(df) = .xx, p = .xxx"],
        ["Regression", "R squared = .xx, F(df1, df2) = x.xx, p = .xxx; B, beta and p for each predictor"],
      ],
    },
    faqs: [
      { q: "Can you build the chapter from my existing analysis?", a: "Yes. Send your outputs and objectives and we write the chapter around them." },
      { q: "What referencing style do you use?", a: "Whatever your institution requires: APA, Harvard, Chicago or a custom style. Tell us in the request form." },
      { q: "Do you help with the discussion chapter too?", a: "We can support discussion and conclusion sections that depend on your results. Mention it in your request." },
      { q: "Do you need my university's thesis template?", a: "It helps. Share the template or guidelines so formatting matches from the first draft." },
    ],
    related: ["research-results-interpretation", "thesis-data-analysis-help", "questionnaire-data-analysis-help"],
  },
  /* ------------------------------------------------------------ 9 */
  {
    slug: "likert-scale-data-analysis", short: "Likert Scale Data Analysis", category: "scales", eyebrow: "Likert scales",
    title: "Likert Scale Data Analysis Help | Ordinal vs Interval | Scape Data",
    description: "Likert scale data analysis help: when to use medians and Mann-Whitney, when composite scores allow t-tests and regression, and how to defend the choice.",
    keywords: "Likert scale data analysis, analyse Likert scale in SPSS, Likert ordinal or interval, Likert scale statistical test, Likert mean interpretation",
    h1: "Likert scale data analysis: ordinal or interval, and which test follows",
    intro: "Likert data triggers the most arguments in thesis defences: is it ordinal, can I use means, can I run a t-test? We apply the position your field accepts, justify it in a sentence you can quote, and analyse accordingly.",
    problems: [
      "You do not know whether to report medians or means",
      "Your supervisor says you cannot use a t-test on Likert data",
      "You have several items per construct and no composite scores",
      "Your questionnaire mixes 5-point and 7-point scales",
    ],
    steps: [
      { t: "Classify your items", d: "Single items versus multi-item scales, because that decides the method." },
      { t: "Test reliability", d: "Cronbach's alpha confirms items belong together before they are averaged." },
      { t: "Build composites", d: "Reverse-code negative items and compute scale scores, with the rule documented." },
      { t: "Choose the test", d: "Parametric on reliable composites, non-parametric on single items or heavy skew." },
    ],
    deliverables: [
      "Item-level frequencies, medians and means",
      "Composite scores with documented reverse-coding",
      "Reliability statistics for each scale",
      "The right test per objective, with a one-line justification",
      "Citations-ready reasoning for your methodology chapter",
    ],
    mistakes: [
      { t: "Averaging items that were never tested for reliability", d: "A composite from an unreliable scale is meaningless. Check alpha first." },
      { t: "Using Pearson on single 5-point items", d: "Spearman is safer for ordinal single items. Reserve Pearson for composites." },
      { t: "Mixing scale lengths without standardising", d: "Combining 5-point and 7-point items needs rescaling or standardising first." },
    ],
    example: {
      setup: "Composite scores built after reliability checks.",
      head: ["Construct", "Items", "Cronbach's alpha", "M (SD)"],
      rows: [["Job satisfaction", "6", ".84", "3.72 (0.61)"], ["Organisational commitment", "8", ".88", "3.55 (0.68)"], ["Work stress", "5", ".79", "2.91 (0.83)"]],
      note: "Illustrative example, not client data.",
    },
    guide: {
      title: "Item or scale? Which test?",
      head: ["Your data", "Treat as", "Typical tests"],
      rows: [
        ["A single Likert item", "Ordinal", "Median, Mann-Whitney, Kruskal-Wallis, Spearman"],
        ["A reliable scale of 4+ items", "Approximately interval composite", "Mean, t-test, ANOVA, Pearson, regression"],
        ["Few categories or heavy skew", "Ordinal", "Non-parametric tests or ordinal logistic regression"],
      ],
    },
    faqs: [
      { q: "Can I use a t-test on Likert data?", a: "On a reliable composite score, many fields accept it. On a single item, use Mann-Whitney. We apply the convention your supervisor or institution expects." },
      { q: "How do I reverse-code items?", a: "For a 5-point scale, new = 6 minus old. We do this, flag which items were reversed and record it in the codebook." },
      { q: "What is a good mean interpretation scale?", a: "Equal-width class intervals such as 1.00 to 1.80 = strongly disagree work for 5-point scales. We use the one in your methodology." },
      { q: "Do you handle 7-point and mixed scales?", a: "Yes. We standardise or rescale as needed and document how." },
    ],
    related: ["cronbach-alpha-reliability-analysis", "questionnaire-data-analysis-help", "factor-analysis-spss-help"],
  },
  /* ------------------------------------------------------------ 10 */
  {
    slug: "cronbach-alpha-reliability-analysis", short: "Cronbach's Alpha Reliability", category: "scales", eyebrow: "Reliability",
    title: "Cronbach's Alpha Reliability Analysis Help | Scale Validation | Scape Data",
    description: "Cronbach's alpha help: reliability for each construct, item-total statistics, 'alpha if item deleted' decisions and how to report scale reliability.",
    keywords: "Cronbach's alpha help, reliability analysis SPSS, Cronbach alpha low fix, alpha if item deleted, scale reliability thesis",
    h1: "Cronbach's alpha and scale reliability: fix a low alpha, report it properly",
    intro: "A low alpha can stall a whole chapter. We run reliability for every construct, find the items pulling it down, advise whether to drop or keep them, and give you the reporting sentence for your methodology.",
    problems: [
      "Your alpha is .58 and your supervisor says the scale is unreliable",
      "'Alpha if item deleted' suggests dropping an item you need for validity",
      "You are unsure whether to reverse-code before running alpha",
      "You have to report reliability for pilot and main study separately",
    ],
    steps: [
      { t: "Check coding first", d: "Reverse-coded items are the top cause of low alpha. We rule that out before anything else." },
      { t: "Run reliability", d: "Alpha, corrected item-total correlations and alpha-if-item-deleted for every construct." },
      { t: "Decide with you", d: "Drop, keep or revise items, weighing statistics against content validity." },
      { t: "Report", d: "A table plus the methodology sentence in the form your university expects." },
    ],
    deliverables: [
      "Reliability table for every scale",
      "Corrected item-total correlations and alpha-if-deleted",
      "Recommendations for weak or redundant items",
      "Pilot versus main study comparison if required",
      "Reporting text for your methodology chapter",
    ],
    mistakes: [
      { t: "Not reverse-coding negatively worded items", d: "This alone can drop alpha by .20 or more." },
      { t: "Deleting items to chase a number", d: "Removing items can hurt content validity. Justify each deletion in terms of both statistics and meaning." },
      { t: "Reporting one alpha for the whole questionnaire", d: "Alpha belongs to a unidimensional scale. Report it per construct." },
    ],
    example: {
      setup: "Reliability summary across three constructs.",
      head: ["Scale", "Items", "Alpha", "Action"],
      rows: [["Customer trust", "6", ".87", "Keep all items"], ["Perceived risk", "5", ".62", "Item 4 weak (corrected r = .12): review"], ["Service quality", "10", ".93", "Check for redundant items"]],
      note: "Illustrative example.",
    },
    guide: {
      title: "How alpha is commonly read",
      head: ["Alpha", "Common reading"],
      rows: [
        ["At or above .90", "Excellent, but check for redundant items"],
        [".80 to .89", "Good"],
        [".70 to .79", "Acceptable"],
        [".60 to .69", "Questionable; acceptable in exploratory work with justification"],
        ["Below .60", "Poor; revise the scale"],
      ],
    },
    faqs: [
      { q: "What is an acceptable Cronbach's alpha?", a: "Most theses use .70 as the benchmark. Exploratory work or short scales sometimes accept .60 with justification." },
      { q: "Can a scale have good alpha but still be invalid?", a: "Yes. Alpha measures internal consistency, not validity. Factor analysis and content review address validity." },
      { q: "Should I use omega instead?", a: "McDonald's omega is often preferred for multidimensional data. We can report both if your supervisor asks." },
      { q: "How is alpha affected by number of items?", a: "More items inflate alpha, which is why very long scales can show high alpha even with weak items." },
    ],
    related: ["factor-analysis-spss-help", "likert-scale-data-analysis", "questionnaire-data-analysis-help"],
  },
  /* ------------------------------------------------------------ 11 */
  {
    slug: "factor-analysis-spss-help", short: "Factor Analysis (EFA and CFA)", category: "scales", eyebrow: "Factor analysis",
    title: "Factor Analysis Help in SPSS | EFA, PCA & CFA | Scape Data",
    description: "Factor analysis help: KMO and Bartlett's test, extraction, rotation, loadings and scree plots in SPSS, with write-up for exploratory and confirmatory work.",
    keywords: "factor analysis SPSS help, exploratory factor analysis help, EFA SPSS, KMO Bartlett test, PCA SPSS, confirmatory factor analysis",
    h1: "Factor analysis help: EFA, PCA and CFA with a clear write-up",
    intro: "Factor analysis involves a stack of decisions: extraction, rotation, number of factors, cut-offs. We make them with you, show the evidence for each, and produce the loadings table and methods paragraph a panel expects.",
    problems: [
      "You do not know whether you need PCA, EFA or CFA",
      "KMO is low or Bartlett's test is not significant",
      "Items load on several factors, or no factor structure appears",
      "You need to justify retaining a number of factors",
    ],
    steps: [
      { t: "Check suitability", d: "Sample adequacy, KMO, Bartlett's test, correlation matrix and communalities." },
      { t: "Extract and decide", d: "Eigenvalues, scree plot and parallel analysis to choose the number of factors." },
      { t: "Rotate and interpret", d: "Promax or varimax chosen on theory, with loadings and cross-loadings reviewed." },
      { t: "Name and report", d: "Factor labels, loadings table, variance explained and the methods paragraph." },
    ],
    deliverables: [
      "Suitability tests with a decision",
      "Scree plot and parallel analysis evidence",
      "Rotated loadings table, cleaned of weak items",
      "Variance explained and reliability for each factor",
      "Methods and results paragraphs ready for your chapter",
    ],
    mistakes: [
      { t: "Using eigenvalue > 1 as the only rule", d: "It often over-extracts. Use the scree plot and parallel analysis too." },
      { t: "Forcing varimax when factors are correlated", d: "Psychological and social constructs usually correlate. An oblique rotation such as promax is often more realistic." },
      { t: "Treating PCA and EFA as the same", d: "PCA summarises variance. EFA models latent constructs. State which one you used and why." },
    ],
    example: {
      setup: "Suitability and extraction summary for a 15-item scale, n = 320.",
      head: ["Check", "Result", "Verdict"],
      rows: [
        ["KMO", ".82", "Adequate (above .60)"],
        ["Bartlett's test", "chi-square(105) = 1,204.3, p < .001", "Data are factorable"],
        ["Factors with eigenvalue > 1", "3", "Confirmed with scree plot and parallel analysis"],
        ["Variance explained", "61.4%", "Acceptable"],
      ],
      note: "Illustrative example, not client data.",
    },
    guide: {
      title: "PCA, EFA or CFA?",
      head: ["Method", "Use when", "Usual software"],
      rows: [
        ["PCA", "Reducing many variables to fewer components", "SPSS, R, Jamovi"],
        ["EFA", "Discovering or checking underlying constructs", "SPSS, R, Jamovi"],
        ["CFA", "Confirming a structure your theory specifies", "AMOS, lavaan, Mplus"],
      ],
    },
    faqs: [
      { q: "What sample size do I need?", a: "Rules of thumb range from 5 to 10 cases per item, with 150 to 300 often cited as a minimum. We advise on your specific case." },
      { q: "What loading cut-off is acceptable?", a: "Common cut-offs are .40 or .50, depending on sample size and field. We apply the one you cite." },
      { q: "Can you do CFA?", a: "Yes, in AMOS or lavaan, with model fit indices and modification advice. See our SEM page for full path models." },
      { q: "What if the structure does not match my instrument?", a: "We report it honestly, test alternatives and help you discuss why the observed structure differs." },
    ],
    related: ["cronbach-alpha-reliability-analysis", "sem-amos-smartpls-help", "likert-scale-data-analysis"],
  },
  /* ------------------------------------------------------------ 12 */
  {
    slug: "mediation-moderation-analysis-help", short: "Mediation and Moderation", category: "advanced", eyebrow: "PROCESS macro",
    title: "Mediation & Moderation Analysis Help | PROCESS Macro | Scape Data",
    description: "Mediation and moderation analysis help with the PROCESS macro: bootstrapped indirect effects, interaction plots, simple slopes and moderated mediation.",
    keywords: "mediation analysis help, moderation analysis SPSS, PROCESS macro help, moderated mediation, bootstrapping indirect effect, simple slopes",
    h1: "Mediation and moderation analysis: PROCESS macro done correctly",
    intro: "Does the mediator carry the effect? Does the moderator change it? We pick the right PROCESS model, run bootstrapped confidence intervals, probe interactions with simple slopes and write the results the way journals and panels expect.",
    problems: [
      "You do not know which PROCESS model number matches your conceptual diagram",
      "The Sobel test is out of favour and your supervisor wants bootstrapping",
      "Your interaction is significant but you cannot explain it",
      "Your model has both a mediator and a moderator",
    ],
    steps: [
      { t: "Map the diagram", d: "Your conceptual model is turned into the correct PROCESS model number and variable roles." },
      { t: "Prepare variables", d: "Mean-centring, dummy coding and covariates set before the model is run." },
      { t: "Run with bootstrapping", d: "Usually 5,000 resamples with bias-corrected confidence intervals." },
      { t: "Probe and plot", d: "Simple slopes, Johnson-Neyman regions and an interaction plot for moderation." },
    ],
    deliverables: [
      "Correct PROCESS model for your conceptual framework",
      "Direct, indirect and total effects with bootstrapped CIs",
      "Interaction plot and simple-slopes analysis",
      "Decision on full or partial mediation",
      "Results paragraph and diagram-ready path table",
    ],
    mistakes: [
      { t: "Relying on the Sobel test", d: "It assumes a normal indirect effect, which is rarely true. Bootstrapped intervals are the current standard." },
      { t: "Skipping mean-centring before interactions", d: "Uncentred predictors create multicollinearity and make coefficients hard to read." },
      { t: "Calling mediation causal without design support", d: "Cross-sectional data show a pattern consistent with mediation, not proof of it. State this in limitations." },
    ],
    example: {
      setup: "Bootstrapped mediation (PROCESS Model 4, 5,000 samples), n = 240.",
      head: ["Path", "B", "SE", "95% CI"],
      rows: [
        ["X to M (a)", "0.52", "0.09", "[0.34, 0.70]"],
        ["M to Y (b)", "0.38", "0.08", "[0.22, 0.54]"],
        ["Direct effect (c')", "0.15", "0.10", "[-0.05, 0.35]"],
        ["Indirect effect (a x b)", "0.20", "0.06", "[0.09, 0.32]"],
      ],
      note: "Illustrative example. The indirect effect's interval excludes zero and the direct effect's includes zero, a pattern consistent with full mediation.",
    },
    guide: {
      title: "Which PROCESS model?",
      head: ["You want to test", "Design", "PROCESS model"],
      rows: [
        ["M explains how X affects Y", "Simple mediation", "Model 4"],
        ["W changes the strength of X to Y", "Simple moderation", "Model 1"],
        ["Mediators in a chain", "Serial mediation", "Model 6"],
        ["Moderation of a mediated effect", "Moderated mediation", "Model 7, 8 or 14"],
      ],
    },
    faqs: [
      { q: "Do I need the PROCESS macro installed?", a: "We handle it. If you want to reproduce results, we include installation steps and the exact command." },
      { q: "Can you do this in R or lavaan?", a: "Yes. We can use lavaan or the mediation package in R if your institution prefers it." },
      { q: "How many bootstrap samples?", a: "5,000 is the usual standard. We use 10,000 where precision matters." },
      { q: "What sample size is enough?", a: "Mediation needs larger samples than simple tests. We advise based on your expected effect sizes." },
    ],
    related: ["regression-analysis-help", "sem-amos-smartpls-help", "research-results-interpretation"],
  },
  /* ------------------------------------------------------------ 13 */
  {
    slug: "sem-amos-smartpls-help", short: "SEM: AMOS and SmartPLS", category: "advanced", eyebrow: "Structural equation modelling",
    title: "SEM Analysis Help | AMOS, SmartPLS & CB-SEM vs PLS-SEM | Scape Data",
    description: "Structural equation modelling help in AMOS and SmartPLS: measurement model, fit indices, validity, path coefficients and write-up for your thesis.",
    keywords: "SEM analysis help, AMOS help, SmartPLS help, PLS-SEM analysis, CB-SEM, structural equation modeling thesis, model fit RMSEA CFI",
    h1: "SEM analysis help: AMOS, SmartPLS, fit indices and a defensible model",
    intro: "SEM combines measurement and structure, which is why it intimidates. We choose between CB-SEM and PLS-SEM for your data, specify and test the model, report fit and validity correctly, and explain each path.",
    problems: [
      "You do not know whether AMOS or SmartPLS fits your study",
      "Your fit indices (RMSEA, CFI) fail the cut-offs",
      "Discriminant validity or AVE values are below the threshold",
      "Modification indices tempt you to add paths without theory",
    ],
    steps: [
      { t: "Choose the approach", d: "CB-SEM for theory testing with adequate sample, PLS-SEM for prediction or smaller samples." },
      { t: "Test the measurement model", d: "Loadings, reliability, AVE and discriminant validity before any paths." },
      { t: "Test the structural model", d: "Path coefficients, R-squared, effect sizes and bootstrapped significance." },
      { t: "Report", d: "Fit table, validity table, path diagram and results paragraphs." },
    ],
    deliverables: [
      "Model specification matching your conceptual framework",
      "Measurement model with reliability and validity tables",
      "Fit indices (CB-SEM) or PLS quality criteria",
      "Path diagram and coefficient table",
      "Hypothesis decisions with reasoning",
    ],
    mistakes: [
      { t: "Picking PLS-SEM only because the sample is small", d: "Small samples are not a licence. Justify the choice by research goal and cite a source." },
      { t: "Adding covariances to chase fit", d: "Every modification needs theoretical justification, not only a lower chi-square." },
      { t: "Ignoring discriminant validity", d: "If constructs overlap too much, structural paths are not interpretable. Check HTMT or Fornell-Larcker." },
    ],
    example: {
      setup: "CB-SEM model fit for a 4-construct model, n = 360.",
      head: ["Index", "Value", "Common threshold"],
      rows: [["chi-square / df", "2.14", "Below 3"], ["CFI", ".95", "At least .90 (.95 ideal)"], ["TLI", ".94", "At least .90"], ["RMSEA", ".058", "Below .08 (.06 ideal)"], ["SRMR", ".046", "Below .08"]],
      note: "Illustrative example, not client data.",
    },
    guide: {
      title: "CB-SEM or PLS-SEM?",
      head: ["Question", "CB-SEM (AMOS)", "PLS-SEM (SmartPLS)"],
      rows: [
        ["Main goal", "Confirm theory and model fit", "Prediction and theory development"],
        ["Sample size", "Larger samples preferred", "Works with smaller samples"],
        ["Distribution", "Assumes multivariate normality (ML)", "No distributional assumptions"],
        ["Model fit indices", "Central to reporting", "Not the main criterion"],
      ],
    },
    faqs: [
      { q: "Which one should I use?", a: "It depends on your goal, sample and what your supervisor accepts. We recommend with reasons you can cite." },
      { q: "Do I need to own the software?", a: "No. We run the models and send you the outputs, diagrams and, where possible, project files." },
      { q: "What sample size do I need?", a: "CB-SEM often wants 200+ cases. PLS-SEM minimums are lower but still depend on model complexity." },
      { q: "Can you rescue a model that fails fit?", a: "We diagnose the cause, suggest theoretically justified changes and report any modifications honestly." },
    ],
    related: ["factor-analysis-spss-help", "mediation-moderation-analysis-help", "thesis-data-analysis-help"],
  },
  /* ------------------------------------------------------------ 14 */
  {
    slug: "kobotoolbox-odk-data-analysis-help", short: "KoboToolbox and ODK Data", category: "prep", eyebrow: "Field data",
    title: "KoboToolbox & ODK Data Cleaning and Analysis Help | Scape Data",
    description: "KoboToolbox, ODK and Google Forms data cleaning and analysis: select-multiple splitting, repeat groups, quality checks, then SPSS, Stata or R analysis.",
    keywords: "KoboToolbox data analysis, ODK data cleaning, Kobo export to SPSS, select multiple Kobo, Google Forms data analysis, field survey data",
    h1: "KoboToolbox and ODK data: from messy export to a clean, analysable dataset",
    intro: "Field-collection exports are rarely analysis-ready: select-multiple columns, repeat groups on separate sheets, labels as codes. We restructure them, run quality checks on interview behaviour, then analyse in the software you need.",
    problems: [
      "Your Kobo export has columns like Q5/a, Q5/b, Q5/c and you do not know how to use them",
      "Repeat groups sit on separate sheets that will not merge to one row per respondent",
      "You need to check for fabricated or rushed interviews",
      "You have to move data from Excel into SPSS, Stata or R with labels intact",
    ],
    steps: [
      { t: "Audit the export", d: "Form structure (XLSForm), column types, repeat groups, metadata and submission patterns." },
      { t: "Restructure", d: "Select-multiple split into labelled 0/1 variables, repeat groups merged or reshaped to the unit you analyse." },
      { t: "Quality-check", d: "Duration, duplicates, skip-logic violations and enumerator patterns." },
      { t: "Analyse and deliver", d: "Labelled dataset in SPSS, Stata or R format, then the analysis your objectives need." },
    ],
    deliverables: [
      "Restructured, labelled dataset in .sav, .dta or CSV",
      "Select-multiple items split into usable variables",
      "Repeat groups merged or reshaped correctly",
      "Data quality report by enumerator and by submission",
      "Analysis of your objectives, if requested",
    ],
    mistakes: [
      { t: "Analysing the raw export directly", d: "Select-multiple columns and coded labels will give wrong frequencies if used as-is." },
      { t: "Ignoring enumerator effects", d: "One enumerator's rushed interviews can bias a whole dataset. Check results per enumerator." },
      { t: "Losing labels during export to SPSS", d: "Without value labels, outputs are unreadable. We map them from your XLSForm." },
    ],
    example: {
      setup: "Typical Kobo and ODK export problems, and the fix.",
      head: ["Export problem", "What we do"],
      rows: [
        ["Select-multiple as Q5/a, Q5/b, Q5/c", "Split into labelled 0/1 variables"],
        ["Repeat groups on separate sheets", "Merged to one row per respondent or household"],
        ["Choice names in column headers", "Mapped to codebook value labels"],
        ["GPS and timestamp metadata", "Used for duration and quality checks, then removed"],
      ],
      note: "Illustrative example.",
    },
    guide: {
      title: "Data quality checks we run",
      head: ["Check", "What it catches"],
      rows: [
        ["Interview duration", "Rushed or fabricated interviews"],
        ["Duplicate submissions", "Same device or identical answers"],
        ["Skip-logic violations", "Answers that should not exist"],
        ["Per-enumerator patterns", "Outlier enumerators"],
      ],
    },
    faqs: [
      { q: "Can you work from my XLSForm?", a: "Yes. The form lets us map choice labels exactly and check skip logic." },
      { q: "Does this work for Google Forms and SurveyCTO?", a: "Yes. Different tools, similar problems. We handle all three." },
      { q: "Can you prepare the data for Stata or R?", a: "Yes. We deliver .dta, .sav, CSV or R-ready files with labels." },
      { q: "Is respondent data kept confidential?", a: "Yes. Files are used only for your project and deleted on request." },
    ],
    related: ["research-data-cleaning-service", "questionnaire-data-analysis-help", "spss-data-analysis-help"],
  },
  /* ------------------------------------------------------------ 15 */
  {
    slug: "sample-size-calculation-help", short: "Sample Size and Power Analysis", category: "advanced", eyebrow: "Study design",
    title: "Sample Size Calculation & Power Analysis Help for Research | Scape Data",
    description: "Sample size calculation and power analysis help for proposals and theses: Cochran, Yamane, G*Power, regression and group comparisons, with defensible justification.",
    keywords: "sample size calculation help, power analysis G*Power, Cochran formula, Yamane formula, sample size for regression, sample size for thesis",
    h1: "Sample size and power analysis: a number your panel will accept",
    intro: "Panels increasingly reject 'we used Yamane' without thought. We calculate the sample size your design and analysis need, using G*Power or the right formula, and write the justification with citations.",
    problems: [
      "Your proposal needs a sample size justified before you collect data",
      "You used Yamane and your supervisor wants power analysis",
      "You do not know the effect size to enter into G*Power",
      "You need to adjust for non-response or clustering",
    ],
    steps: [
      { t: "Understand the design", d: "Population, outcome, planned analysis and any subgroups." },
      { t: "Choose the method", d: "Cochran or Yamane for descriptive surveys, G*Power for tests, event-based rules for logistic regression." },
      { t: "Set the assumptions", d: "Alpha, power, effect size with literature-based justification." },
      { t: "Write it up", d: "Calculation steps, citations and non-response adjustment for your methodology." },
    ],
    deliverables: [
      "Sample size calculation with every step shown",
      "G*Power screenshots or formula workings",
      "Effect-size justification from the literature",
      "Non-response and design-effect adjustment",
      "A paragraph for Chapter 3",
    ],
    mistakes: [
      { t: "Using Yamane for everything", d: "It suits descriptive surveys of a finite population, not group comparisons or regression." },
      { t: "Choosing a medium effect size with no source", d: "Cite earlier studies or a pilot. 'Medium by convention' is the weakest justification." },
      { t: "Forgetting non-response", d: "If you expect 20% non-response, inflate the target so the final sample still meets the requirement." },
    ],
    example: {
      setup: "Different designs need different calculations.",
      head: ["Design", "Method", "Inputs"],
      rows: [
        ["Descriptive survey, large population", "Cochran", "Confidence level, margin of error, proportion"],
        ["Compare two groups", "G*Power, t-test", "Effect size d, alpha, power"],
        ["Multiple regression", "G*Power, F test", "f-squared, alpha, power, predictors"],
        ["Logistic regression", "Events per variable", "Expected event rate, predictors"],
      ],
      note: "Illustrative example.",
    },
    guide: {
      title: "Common defaults, and when they apply",
      head: ["Setting", "Common default", "Notes"],
      rows: [
        ["Alpha", ".05", "Stricter if running many tests"],
        ["Power", ".80", ".90 for high-stakes work"],
        ["Cohen's d", "0.5 (medium)", "Justify with prior literature"],
        ["Margin of error (survey)", "5%", "Smaller margins need larger samples"],
      ],
    },
    faqs: [
      { q: "Is Yamane acceptable?", a: "For descriptive surveys of a known finite population, often yes. For testing hypotheses, power analysis is better." },
      { q: "What if I already collected my data?", a: "We run a post-hoc sensitivity analysis showing the smallest effect your sample could detect." },
      { q: "Can you handle cluster or stratified sampling?", a: "Yes. We adjust for design effects and allocate across strata." },
      { q: "Will you cite sources for the justification?", a: "Yes. Each assumption is tied to a reference you can include." },
    ],
    related: ["thesis-data-analysis-help", "regression-analysis-help", "questionnaire-data-analysis-help"],
  },
];

export const getPage = (slug) => landingPages.find((p) => p.slug === slug);
